language: python
python:
  - "3.6"
sudo: required
dist: bionic
before_install:
  - virtualenv --version
  - virtualenv ~/virtualenv/newenv
  - deactivate
  - virtualenv --version
  - source ~/virtualenv/newenv/bin/activate
  - virtualenv --version
install: skip
script:
  - python -W error::DeprecationWarning -c 'import distutils'
