language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: bionic
before_install:
  - python -c 'import os, virtualenv; virtualenv.install_distutils(os.environ["VIRTUAL_ENV"])'
  - virtualenv --version
install: skip
script:
  - python -W error::DeprecationWarning -c 'import distutils'
