language: python
python:
  - "3.6"
sudo: required
dist: bionic
before_install:
  - deactivate
  - pip install virtualenv==16.3.0
  - rm -r ~/virtualenv/python3.6.7
  - virtualenv --python=/opt/python/3.6.7/bin/python3.6.7 ~/virtualenv/python3.6.7
  - source ~/virtualenv/python3.6/bin/activate
script:
  - python -W error::DeprecationWarning -c 'import distutils'
