language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: bionic
before_install:
  - virtualenv ~/virtualenv/tmpenv
  - DISTUTILS_PATH=lib/python$TRAVIS_PYTHON_VERSION/distutils
  - rm -r ~/virtualenv/python$TRAVIS_PYTHON_VERSION/$DISTUTILS_PATH
  - mv ~/virtualenv/tmpenv/$DISTUTILS_PATH ~/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - rm -r ~/virtualenv/tmpenv
install: skip
script:
  - python -W error::DeprecationWarning -c 'import distutils'
