language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: bionic
before_install:
  - virtualenv /tmp/env --no-setuptools --no-pip --no-wheel
  - DISTUTILS_PATH=lib/python$TRAVIS_PYTHON_VERSION/distutils
  - rm -r ~/virtualenv/python$TRAVIS_PYTHON_VERSION/$DISTUTILS_PATH
  - mv /tmp/env/$DISTUTILS_PATH ~/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - virtualenv --version
install: skip
script:
  - python -W error::DeprecationWarning -c 'import distutils'
